version: '3.8'
services:
  openvpn:
    build: .
    image: duckduckio/openvpn:latest
    container_name: openvpn
    # env_file:
    #   - ./.env
    ports:
      - 443:1194
    volumes:
      - ./configs:/root/client-configs
    #   - ./config/letsencrypt:/etc/letsencrypt
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges
    restart: unless-stopped
