version: '3.8'
services:
  ocserv:
    image: duckduckio/openvpn:latest
    container_name: openvpn
    env_file:
      - ./.env
    ports:
      - 443:1194
    volumes:
      - ./config:/etc/openvpn
      - ./config/certs:/etc/openvpn/certs
    #   - ./config/letsencrypt:/etc/letsencrypt
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges
    restart: unless-stopped
