services:
  openvpn:
    image: pandasrun/openvpn:latest
    container_name: openvpn
    environment:
      - DOMAIN=
      #- FORWARD_GOST=true  # optional; forward all TCP to gost, default false if unset
      #- FORWARD_IPV4=      # optional; forward all traffic to a public IPv4 when FORWARD_GOST=false
      #- FORWARD_IPV6=      # optional; forward all traffic to a public IPv6 when FORWARD_GOST=false
      - EXPOSE_PORT=443     # expose port, should be same as your public port in ports section
    networks:
      - ipv6
    devices:
      - /dev/net/tun
    ports:
      - 443:1194
      - 443:1194/udp
    volumes:
      - ./config:/etc/openvpn
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges
    restart: unless-stopped

networks:
  ipv6:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB8::/112
